.\"
.TH TPMNV_LOCK 8 "2020-05-10" "tboot" "User Manuals"
.SH NAME
tpmnv_lock \- lock TPM NV storage
.SH SYNOPSIS
.B tpmnv_lock
.RB [\| -f \|]
.RB [\| -h \|]
.SH DESCRIPTION
.B tpmnv_lock
can be used to lock TPM NV storage.
.SH OPTIONS
.TP
.BI -f\ 
Lock without prompting the user.
.TP
.BI -h\ 
Print the help text.
.SH "SEE ALSO"
.BR tpm_nvinfo (8)
